######################################################################
# Automatically generated by qmake (2.01a) Tue May 3 00:11:36 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += byte_converter.h
SOURCES += byte_converter.cpp main.cpp
